use_frameworks!

platform :ios, '8.0'

target 'NLCircularProgressView_Example' do
  pod 'NLCircularProgressView', :path => '../'

  target 'NLCircularProgressView_Tests' do
    inherit! :search_paths

    
  end
end
